# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Probability and Statistics Applications for Civil Engineers
author: Robert Lanzafame, Miguel Mendoza Lugo and Patricia Mares Nasarre
logo: logo sketch and tud.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: learn_prob.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
#  announcement: "⚠️ This is not the final version of the book! The new version will be ready by July 1.⚠️"
  home_page_in_navbar: false
  google_analytics_id: G-3M271KTT5T
  extra_navbar: |
      <div>
          <IMG SRC="https://raw.githubusercontent.com/mbakker7/exploratory_computing_with_python/master/tudelft_logo.png" WIDTH=200 ALIGN="center">
      </div>
#  use_issues_button: true
#  use_repository_button: true
